#!/bin/bash
sudo set -ex

sudo mkdir -p /etc/swift
cd /etc/swift
echo " >>>>> Downloading the config files. >>>>> ."
echo ""
sudo curl -o /etc/swift/account-server.conf https://raw.githubusercontent.com/tino1b2be/swift-on-vm/master/account-server-sample.conf
sudo curl -o /etc/swift/container-server.conf https://raw.githubusercontent.com/tino1b2be/swift-on-vm/master/container-server-sample.conf
sudo curl -o /etc/swift/object-server.conf https://raw.githubusercontent.com/tino1b2be/swift-on-vm/master/object-server-sample.conf
sudo curl -o /etc/swift/swift.conf https://raw.githubusercontent.com/tino1b2be/swift-on-vm/master/swift-sample.conf
sudo curl -o $HOME/testrc https://raw.githubusercontent.com/tino1b2be/swift-on-vm/master/swiftrc

sudo chown -R swift:swift /srv/node
sudo mkdir -p /var/cache/swift
sudo chown -R root:swift /var/cache/swift
sudo chmod -R 775 /var/cache/swift

#create thee ring builder files
echo " >>>>> Creating the rings >>>>>"
#accounts ring
sudo swift-ring-builder account.builder create 10 3 1
sudo swift-ring-builder account.builder add --region 1 --zone 1 --ip 127.0.0.1 --port 6002 --device sdb --weight 100
sudo swift-ring-builder account.builder add --region 1 --zone 1 --ip 127.0.0.1 --port 6002 --device sdc --weight 100
sudo swift-ring-builder account.builder add --region 1 --zone 1 --ip 127.0.0.1 --port 6002 --device sdd --weight 100
# rebalance
sudo swift-ring-builder account.builder rebalance

#containers ring
sudo swift-ring-builder container.builder create 10 3 1
sudo swift-ring-builder container.builder add --region 1 --zone 1 --ip 127.0.0.1 --port 6001 --device sdb --weight 100
sudo swift-ring-builder container.builder add --region 1 --zone 1 --ip 127.0.0.1 --port 6001 --device sdc --weight 100
sudo swift-ring-builder container.builder add --region 1 --zone 1 --ip 127.0.0.1 --port 6001 --device sdd --weight 100
#rebalance
sudo swift-ring-builder container.builder rebalance

#objects ring
sudo swift-ring-builder object.builder create 10 3 1
sudo swift-ring-builder object.builder add --region 1 --zone 1 --ip 127.0.0.1 --port 6000 --device sdb --weight 100
sudo swift-ring-builder object.builder add --region 1 --zone 1 --ip 127.0.0.1 --port 6000 --device sdc --weight 100
sudo swift-ring-builder object.builder add --region 1 --zone 1 --ip 127.0.0.1 --port 6000 --device sdd --weight 100
#rebalance
sudo swift-ring-builder object.builder rebalance

echo "the contents of the rings are:"
echo "=============================="
swift-ring-builder account.builder
echo "=============================="
swift-ring-builder container.builder
echo "=============================="
sudo swift-ring-builder object.builder
echo "=============================="

sudo chown -R root:swift /etc/swift

echo " >>>>> restarting services >>>>>"
sudo service memcached restart
sudo service swift-proxy restart

sudo swift-init all restart

echo " Sourcing the env variables for authentication with swift."
source $HOME/testrc

echo "Run 'swift stat' to verify operation"