#!/bin/bash
set -ex

sudo mkdir -p /etc/swift
cd /etc/swift

echo " >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>"
echo ""
echo " >>>>>>>>>> Downloading the config files. >>>>>>>>>>>>>"
echo ""
echo " >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>"

sudo curl -o /etc/swift/proxy-server.conf https://raw.githubusercontent.com/tino1b2be/swift-on-vm/v0.1/config_files/proxy-server-sample.conf
sudo curl -o /etc/swift/account-server.conf https://raw.githubusercontent.com/tino1b2be/swift-on-vm/v0.1/config_files/account-server-sample.conf
sudo curl -o /etc/swift/container-server.conf https://raw.githubusercontent.com/tino1b2be/swift-on-vm/v0.1/config_files/container-server-sample.conf
sudo curl -o /etc/swift/object-server.conf https://raw.githubusercontent.com/tino1b2be/swift-on-vm/v0.1/config_files/object-server-sample.conf
sudo curl -o /etc/swift/swift.conf https://raw.githubusercontent.com/tino1b2be/swift-on-vm/v0.1/config_files/swift-sample.conf
sudo curl -o $HOME/swiftrc https://raw.githubusercontent.com/tino1b2be/swift-on-vm/v0.1/scripts/swiftrc

sudo chown -R swift:swift /srv/node
sudo mkdir -p /var/cache/swift
sudo chown -R root:swift /var/cache/swift
sudo chmod -R 775 /var/cache/swift

cd /etc/swift
#create thee ring builder files
echo " >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>"
echo ""
echo " >>>>>>>>>>>>>>> Creating the rings >>>>>>>>>>>>>>>>>>>"
echo ""
echo " >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>"
#accounts ring
sudo swift-ring-builder account.builder create 10 3 1
sudo swift-ring-builder account.builder add --region 1 --zone 1 --ip 127.0.0.1 --port 6002 --device sdb --weight 100
sudo swift-ring-builder account.builder add --region 1 --zone 1 --ip 127.0.0.1 --port 6002 --device sdc --weight 100
sudo swift-ring-builder account.builder add --region 1 --zone 1 --ip 127.0.0.1 --port 6002 --device sdd --weight 100
# rebalance
sudo swift-ring-builder account.builder rebalance

#containers ring
sudo swift-ring-builder container.builder create 10 3 1
sudo swift-ring-builder container.builder add --region 1 --zone 1 --ip 127.0.0.1 --port 6001 --device sdb --weight 100
sudo swift-ring-builder container.builder add --region 1 --zone 1 --ip 127.0.0.1 --port 6001 --device sdc --weight 100
sudo swift-ring-builder container.builder add --region 1 --zone 1 --ip 127.0.0.1 --port 6001 --device sdd --weight 100
#rebalance
sudo swift-ring-builder container.builder rebalance

#objects ring
sudo swift-ring-builder object.builder create 10 3 1
sudo swift-ring-builder object.builder add --region 1 --zone 1 --ip 127.0.0.1 --port 6000 --device sdb --weight 100
sudo swift-ring-builder object.builder add --region 1 --zone 1 --ip 127.0.0.1 --port 6000 --device sdc --weight 100
sudo swift-ring-builder object.builder add --region 1 --zone 1 --ip 127.0.0.1 --port 6000 --device sdd --weight 100
#rebalance
sudo swift-ring-builder object.builder rebalance

echo "the contents of the rings are:"
echo "=============================="
swift-ring-builder account.builder
echo "=============================="
swift-ring-builder container.builder
echo "=============================="
sudo swift-ring-builder object.builder
echo "=============================="

sudo chown -R root:swift /etc/swift
echo ""
echo " >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>"
echo ""
echo " >>>>>>>>>>>>>>> restarting services >>>>>>>>>>>>>>>>>>"
echo ""
echo " >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>"
echo ""
sudo service memcached restart
sudo service swift-proxy restart

sudo swift-init all restart
echo " >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>"
echo ""
echo " Sourcing the env variables for authentication with swift."
echo ""
echo " >>> #### Run 'swift stat' to verify operation #### >>>>>>>"
echo ""
echo " >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>"
source $HOME/testrc

echo "Run 'swift stat' to verify operation"
